baseurl = "https://igawa.blog/"
languageCode = "ja"
title = "For myself tomorrow"
# Enable comments by entering your Disqus shortname
disqusShortname = "ta.igawa"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-40396882-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"

[permalinks]
    post = "/blog/:year/:month/:day/:filename/"

[params]
    # Tell me who you are
    author = "igawa.taiichi"
    location = "Japan - Shimane"
    site_description = "明日の自分のためのノート"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](https://github.com/ppoffice)."
    avatar = "css/images/avatar.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # ここに セクション を加えるとHOMEに出力することができる
    mainSections = ["post", "ml", "c-sharp","til", "golang", "java", "git", "Python", "aws"]

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = true
    label  = "git"
    link   = "tags/git"

[[params.menu]]
    before = true
    label  = "PostgreSQL"
    link   = "tags/postgresql"

[[params.menu]]
    before = true
    label  = "linux"
    link   = "tags/linux/"

[[params.menu]]
    before = true
    label  = "java"
    link   = "tags/java"

[[params.menu]]
    before = true
    label  = "Python"
    link   = "blog/2016/01/01/archives"

[[params.menu]]
    before = true
    label  = "C#"
    link   = "c-sharp/archives/"

[[params.menu]]
    before = true
    label  = "golang"
    link   = "golang/"

[[params.menu]]
    before = true
    label  = "aws"
    link   = "aws/"

[[params.menu]]
    before = true
    label  = "機械学習"
    link   = "ml/archives/"

[[params.menu]]
    before = true
    label  = "ショートカット"
    link   = "cheat/shortcut/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/tigawa"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "tigawa"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "igawa.taiichi"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "ttigawa"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tag_cloud = true
    tags = true

[outputs]
    section = ["JSON", "HTML"]
